[manifest] # Header for the file, only once at the top
version = "0.1.0"
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
end
timer_checkpoint('debug', 'draw')
'''
position = "at"
payload = '''
end
timer_checkpoint('debug', 'draw')
G.BTTI.MODDRAW_AFTER()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
love.graphics.setCanvas(G.AA_CANVAS)
love.graphics.push()
'''
position = "at"
payload = '''
G.BTTI.MODDRAW()
love.graphics.setCanvas(G.AA_CANVAS)
love.graphics.push()
'''
match_indent = true
